### ISSUE TITLE
Odd Errors in Log

### ISSUE THREAD

**Issue by mr337** [aws-robotics/cloudwatchmetrics-ros1#46]
I am seeing weird errors in the logs about the Cloudwatch regarding timestamps of the metrics. The only metrics currently running are from https://github.com/aws-robotics/health-metrics-collector-ros1.

The error is:
```
[ WARN] [1593088848.837626459, 903.889000000]: [AWSErrorMarshaller] Encountered AWSError 'InvalidParameterValue': The 
parameter MetricData.member.1.Timestamp must specify a time within the past two weeks.
The parameter MetricData.member.2.Timestamp must specify a time within the past two weeks.
The parameter MetricData.member.3.Timestamp must specify a time within the past two weeks.
The parameter MetricData.member.4.Timestamp must specify a time within the past two weeks.
The parameter MetricData.member.5.Timestamp must specify a time within the past two weeks.
The parameter MetricData.member.6.Timestamp must specify a time within the past two weeks.
[ERROR] [1593088848.837759364, 903.889000000]: [AWSClient] HTTP response code: 400
Exception name: InvalidParameterValue
Error message: The parameter MetricData.member.1.Timestamp must specify a time within the past two weeks.
The parameter MetricData.member.2.Timestamp must specify a time within the past two weeks.
The parameter MetricData.member.3.Timestamp must specify a time within the past two weeks.
The parameter MetricData.member.4.Timestamp must specify a time within the past two weeks.
The parameter MetricData.member.5.Timestamp must specify a time within the past two weeks.
The parameter MetricData.member.6.Timestamp must specify a time within the past two weeks.
5 response headers:
connection : close
content-length : 804
content-type : text/xml
date : Thu, 25 Jun 2020 12:40:48 GMT
x-amzn-requestid : 71391052-b267-4f7e-ac62-138315b23fa4
[ WARN] [1593088848.837841133, 903.889000000]: [AWSClient] If the signature check failed. This could be because of a $ime skew. Attempting to adjust the signer.
```

Here is a single metric from the `metrics` topic. The `time_stamp` is live and current and not skewed at all.
```
 - 
    header: 
      seq: 0
      stamp: 
        secs: 1593088888
        nsecs: 394534588
      frame_id: ''
    metric_name: "cpu_usage_core_2"
    unit: "percent"
    value: 90.9923629761
    time_stamp: 
      secs: 1593088888
      nsecs: 394534588
    dimensions: 
      - 
        name: "robot_id"
        value: "4a54bac8-efb7-47a4-9ee5-493d928ae446"
      - 
        name: "category"
        value: "RobotHealth"
```

Another odd behavior is we do get metrics in CW
![blah](https://user-images.githubusercontent.com/413937/85722251-b62e9d00-b6b7-11ea-94fd-2315481fcfe5.png)

Running version: `Version: 2.2.1-1xenial-20200330-153748+0000`
